# **Notebook 1: Establishing the Data**

# AQUIRE REMOTE DATA

### Install & Import Dependencies

In [1]:
!pip install kagglehub -q

import kagglehub
import os
import pandas as pd

### Download Dataset From Kaggle

In [2]:
data_path = kagglehub.dataset_download("andrewsundberg/college-basketball-dataset")
print("Path to dataset files:", data_path)

# List files
print(os.listdir(data_path))

Path to dataset files: /home/codespace/.cache/kagglehub/datasets/andrewsundberg/college-basketball-dataset/versions/10
['cbb18.csv', 'cbb20.csv', 'cbb13.csv', 'cbb22.csv', 'cbb19.csv', 'cbb21.csv', 'cbb24.csv', 'cbb25.csv', 'cbb.csv', 'cbb15.csv', 'cbb23.csv', 'cbb14.csv', 'cbb17.csv', 'cbb16.csv']

### Load CSV File and View Header

In [3]:
df = pd.read_csv(f"{data_path}/cbb.csv")
df.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

# How to Get the Data

The data comes from the Kaggle dataset: “College Basketball Dataset” by Andrew Sundberg

**Direct Link**: https://www.kaggle.com/datasets/andrewsundberg/college-basketball-dataset

To download this data, it can be acquired from the dataset page on Kaggle by clicking "Download" and then saving the zip file to a working directory. This csv can then be imported using pandas.read_csv()

Another way to download this data is used in this notebook, using "kagglehub.dataset_download" which automatically downloads the dataset into a reproducible local directory.

# Who Produced the Data and How



The dataset was created and is regularly updated by Andrew Sundberg, a Kaggle contributor who compiled NCAA Division I men’s basketball statistics across twelve seasons (2013–2024) into a single standardized dataset. Sundberg collected team performance data from publicly available NCAA statistical spreadsheets, cleaned and standardized each season’s file, and then merged them into one CSV (cbb.csv). Once complete, he added a year column to show the season associated with each team entry.

This dataset includes a wide range of features, including not just basic statistics such as games played and games won, but also more advanced attributes such as team metadata, efficiency metrics, offensive and defensive performance, shooting percentages, postseason outcomes, and other analytics that are beneficial for tournament analysis, machine learning models, and more.

# COLS Table - Describing Features

In [4]:
cols_table = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Non-Null Count": df.notnull().sum().values # the non-null values are important for columns like "POSTSEASON" and "SEED" to see which teams make the NCAA men's tournament (March Madness)
})

cols_table

        Column Data Type  Missing Values  Non-Null Count
0         TEAM       str               0            3885
1         CONF       str               0            3885
2            G     int64               0            3885
3            W     int64               0            3885
4        ADJOE   float64               0            3885
5        ADJDE   float64               0            3885
6      BARTHAG   float64               0            3885
7        EFG_O   float64               0            3885
8        EFG_D   float64               0            3885
9          TOR   float64               0            3885
10        TORD   float64               0            3885
11         ORB   float64               0            3885
12         DRB   float64               0            3885
13         FTR   float64               0            3885
14        FTRD   float64               0            3885
15        2P_O   float64               0            3885
16        2P_D   float64               0            3885
17        3P_O   float64               0            3885
18        3P_D   float64               0            3885
19       ADJ_T   float64               0            3885
20         WAB   float64               0            3885
21  POSTSEASON       str            3137             748
22        SEED   float64            3137             748
23        YEAR     int64               0            3885